# Generated by Django 5.1.1 on 2024-09-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("party", models.CharField(max_length=255)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="election.election",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_name", models.CharField(max_length=255)),
                ("voter_email", models.EmailField(max_length=254, unique=True)),
                (
                    "voter_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                (
                    "voter_province",
                    models.CharField(
                        choices=[
                            ("Kigali", "Kigali"),
                            ("North", "North"),
                            ("East", "East"),
                            ("West", "West"),
                            ("South", "South"),
                        ],
                        max_length=50,
                    ),
                ),
                ("voter_phone", models.CharField(max_length=15)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="election.candidate",
                    ),
                ),
            ],
            options={
                "unique_together": {("voter_email", "candidate")},
            },
        ),
    ]
