# Generated by Django 5.0.7 on 2024-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auca_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
