# Generated by Django 5.0.7 on 2024-09-13 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0003_candidate_email_alter_candidate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(
                    2024, 9, 13, 16, 37, 22, 145876, tzinfo=datetime.timezone.utc
                ),
                upload_to="contestants_images/",
            ),
            preserve_default=False,
        ),
    ]
