# Generated by Django 5.0.7 on 2024-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0004_candidate_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter_email",
            field=models.EmailField(max_length=254),
        ),
    ]
