# Generated by Django 5.0.7 on 2024-09-13 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0006_alter_candidate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
    ]
