# Generated by Django 5.0.7 on 2024-09-13 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0007_alter_candidate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("email", "election")},
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("voter_email", "election")},
        ),
    ]
